apiVersion: v1
kind: Secret
metadata:
  name: quiz-ruoyi-secret
  namespace: quiz-ruoyi
type: Opaque
stringData:
  mysql-root-password: "please-change-root-password"
  mysql-database: "ry_vue"
  mysql-user: "ruoyi"
  mysql-password: "please-change-mysql-password"
  redis-password: "please-change-redis-password"
  token-secret: "please-change-token-secret"
